services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: vetforumindia
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./vetforum-backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=vetforumindia
      - PORT=4000
    depends_on:
      - db
    command: sh -c "npm install && npm start"

  frontend:
    build: ./vetforum-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    command: sh -c "npm install && npm run build && npm run preview"

volumes:
  db_data:
